version: 0.2

env:
  variables:
    TF_VERSION: "1.9.5"

phases:
  install:
    commands:
      - echo "Installing Terraform $TF_VERSION"
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init -input=false

  build:
    commands:
      - echo "Planning Terraform"
      - terraform plan -input=false -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -input=false -auto-approve tfplan

artifacts:
  files:
    - "**/*"
